### ISSUE TITLE
Incompability with OpenTerrainGenerator

### ISSUE THREAD

**Issue by MalTeeez** [EndersMagic/EnderMagic#74]
Crash occurs on OTG World join,
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-12-31 19:15:07 CET
Description: Ticking memory connection

java.lang.NullPointerException
    at net.minecraft.world.gen.structure.MapGenStronghold.generatePositions(MapGenStronghold.java:141)
    at net.minecraft.world.gen.structure.MapGenStronghold.getNearestStructurePos(MapGenStronghold.java:77)
    at com.pg85.otg.forge.world.ForgeWorld.getNearestStructurePos(ForgeWorld.java:1189)
    at com.pg85.otg.forge.generator.OTGChunkGenerator.getNearestStructurePos(OTGChunkGenerator.java:492)
    at net.minecraft.world.gen.ChunkProviderServer.getNearestStructurePos(ChunkProviderServer.java:305)
    at ru.mousecray.endmagic.init.EMEvents.onPlayerEnter(EMEvents.java:228)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_299_EMEvents_onPlayerEnter_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:377)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

       | LCHIJA | openterraingenerator        | v9.3                     | OpenTerrainGenerator-1.12.2-v9.3.jar      | None                                     
       | LCHIJA | endmagic                          | 1.4.7b                  | endmagic-1.4.7b.jar                                  | None 

That should be all the useful info, happy to provide more if needed,
Happy new Year!

**Comment by hohserg1** [comment]
Happy new Year!
Can you provide used version of forge and your configuration of OTG?
I tried to reproduce bug with follow modpack: https://www.curseforge.com/minecraft/modpacks/incompability-with-openterraingenerator (wait for approve modpack by moderator of curse)
And I didn't find this bug.

**Comment by hohserg1** [comment]
Too long awaiting of approvement. I publish the modpack just here
[Incompability with OpenTerrainGenerator.zip](https://github.com/EndersMagic/EnderMagic/files/5758870/Incompability.with.OpenTerrainGenerator.zip)

**Comment by MalTeeez** [comment]
Here is the full crash report: 
https://gist.github.com/MalTeeez/32764ba55892ca77f2cb588b41dd16bd

I should note that this uses a special version of OTG which combines both Biome Bundle(OTG) and Biome's O Plenty,
Thank you for answering so fast!

**Comment by MalTeeez** [comment]
Well after another round of testing the problem seems to have fixed itself(I like those bugs) - so ill come back here with more information if the issue reoccurs.

**Comment by hohserg1** [comment]
Ok. I will close issue if the problem is solved. 
Reopen, if such problem appears again, and also try follow actions:
1. remove EM from modpack
2. enter to world
3. launch vanilla ender eye
It must give similar crash because EM gets stronghold position just like the vanilla ender eye.

Thank you for creating a modpack with Ender'sMagic!
